name: Sync Marketplace Docs

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Marketplace Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyYAML requests mkdocs mkdocs-material

      - name: Generate Docs from NML-Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/generate_docs.py

      - name: Build MkDocs Site
        run: mkdocs build

      - name: Deploy to GitHub Pages (peaceiris)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          enable_jekyll: false
