name: Sync GitHub Actions Marketplace

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2am

jobs:
  build-marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Marketplace Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate docs from action repos
        run: python .github/scripts/generate_docs.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION_ORG: central-actions-org  # <- set your org name
